data: '/home/linjunyang/pku/data/'
logF: 'experiments/'
refF: '/home/linjunyang/nist/nist03.tok.ref'
epoch: 20
batch_size: 64
valid_batch_size: 16
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
learning_rate: 0.0009
max_grad_norm: 15
learning_rate_decay: 0.7
start_decay_at: 3
emb_size: 512
hidden_size: 512
dec_num_layers: 3
enc_num_layers: 3
bidirectional: True
dropout: 0.3
max_time_step: 100
eval_interval: 10000
save_interval: 1000
metrics: ['bleu']
shared_vocab: False
beam_size: 10
unk: False
schedule: False
schesamp: False

